targets:
  $default:
    auto_apply_builders: true
    builders:
      drift_dev:
        options:
            generate_connect_constructor: true
            apply_converters_on_variables: true
      drift_dev|not_shared:
        enabled: true
        options:
            generate_connect_constructor: true
            apply_converters_on_variables: true
      drift_dev|preparing_builder:
        enabled: true
        options:
            generate_connect_constructor: true
            apply_converters_on_variables: true
  
  